### ISSUE TITLE
Restore graph cannot capture node position from the .RDS

### ISSUE THREAD

**Issue by allenzhuaz** [allenzhuaz/hgraphapp#11]
The node position can be updated when uploading the same data the second time

**Comment by nanxstats** [comment]
@XDeng0921 will try the `shinyjs::delay()` recipe.

**Comment by nanxstats** [comment]
Fixed by https://github.com/allenzhuaz/hgraphapp/commit/064206cfbacead2c73e57dad91d86896ded282e7 and https://github.com/allenzhuaz/hgraphapp/commit/1a92c203c93e145ab4376d4fcb5814d8dfec37bf.
