### ISSUE TITLE
UI Input planning (reformat layout)

### ISSUE THREAD

**Issue by allenzhuaz** [allenzhuaz/hgraphapp#20]
also an easier solution for restore a dynamic shinyMatrix:

One way is
- [x] Move the items under `Ellipses` and `Color and Legend` subt tabsets from `Format` to `Hypothesis` tab
- [x] Move the items under `Connections` from `Format` to `Transition` tab

We can also consider adding popup window for details format setting, i.e. digits, heights, widths.

**Comment by nanxstats** [comment]
👍  I think this new structure makes more sense to me, because it's grouping by the input parameter's semantic category, instead of by their technical category.
