### ISSUE TITLE
 hypothesis Matrix add a new row expects a delay action to output

### ISSUE THREAD

**Issue by allenzhuaz** [allenzhuaz/hgraphapp#27]
We observed when adding a new row in hypothesis shinyMatrix, it could result in a messy group labels, since the values are all empty.

Could add a check condition to delay output the new node

**Comment by XDeng0921** [comment]
Fixed in https://github.com/allenzhuaz/hgraphapp/pull/28#issue-1274062242. 
Please review and merge if no issues.

**Comment by nanxstats** [comment]
Fixed by https://github.com/allenzhuaz/hgraphapp/pull/28
