### ISSUE TITLE
Allow transition weight input simple calculation

### ISSUE THREAD

**Issue by allenzhuaz** [allenzhuaz/hgraphapp#29]
current weight convert character to numeric, so the following input examples will return to `NA`, cannot be display in the plot:

- `1/3` 
- `0.025*0.5` 
- `0.025*(1-1/2)`
- `sqrt(2)` 
- `(0.5)^2`
- `exp(-1)`

**Comment by nanxstats** [comment]
If this is **really** needed, you probably want to check [this](https://stackoverflow.com/questions/18369913/) out on safely evaluating arithmetic expressions in R.

**Comment by nanxstats** [comment]
If this is only for displaying purposes, we can test if something is likely a numeric or character first, then decide if it should be converted to numeric (or just kept as character if the plotting code accepts that):

```r
is_numerical <- function (x) !is.na(suppressWarnings(as.numeric(x)))
is_numerical("1/3")
is_numerical("sqrt(2)")
```

(If the values ever need to be evaluated for computation, then check [this](https://stackoverflow.com/questions/18369913/) out for safely evaluating arithmetic expressions in R.)

**Comment by allenzhuaz** [comment]
> If this is only for displaying purposes, we can test if something is likely a numeric or character first, then decide if it should be converted to numeric (or just kept as character if the plotting code accepts that):
> 
> ```r
> is_numerical <- function (x) !is.na(suppressWarnings(as.numeric(x)))
> is_numerical("1/3")
> is_numerical(0.333)
> is_numerical("sqrt(2)")
> ```
> 
> (If the values ever needed to be evaluated for computation, then check [this](https://stackoverflow.com/questions/18369913/) out for safely evaluating arithmetic expressions in R.)

That's a good idea! At least from my experience, if the input value is like `a+b`, `a-b`, `a*b` i.e. two or more numbers with `+`, `-`, `*` operation, we expect to display the calculated result. Other cases like a single number with fraction `n/m`, `n^m`, `\sqrt{2}`, may consider use latex math or unicode to display the character directly.

**Comment by allenzhuaz** [comment]
just realized `hGraph` intend to restrict transition weights to be numeric type:
https://github.com/allenzhuaz/gMCPmini/blob/6f36713ad24f8d53433be30dec6c5103cd7b1663/R/hgraph.R#L220

So an easier solution is to just parse the weight text, if the text only contains arithmetic operators. Otherwise, will print error message from the hGraph's logic, even if  the text is not in safely environment.
